# Generated by Django 2.0.6 on 2018-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicroles', '0004_auto_20180630_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrole',
            name='uid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
