# Generated by Django 2.1.2 on 2018-10-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicroles', '0005_auto_20180701_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicrole',
            old_name='uid',
            new_name='discord_id',
        ),
    ]
