# Generated by Django 2.1.2 on 2018-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicroles', '0006_auto_20181027_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrole',
            name='discord_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
