# Generated by Django 2.1.2 on 2018-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicroles', '0007_auto_20181027_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrole',
            name='discord_id',
            field=models.TextField(unique=True),
        ),
    ]
