#!/usr/bin/env bash

export POSTGRES_HOST='db'
export POSTGRES_USER='postgres'
export POSTGRES_DB='postgres'

export PGHOST=$POSTGRES_HOST
export PGUSER=$POSTGRES_USER
export PGPASSWORD=$POSTGRES_PASSWORD
export PGDATABASE=$POSTGRES_DB

wait-for-it db:5432
pipenv run "$@"