# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: ".*(\\.vscode).*"
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: worker-lint
        name: worker lint
        entry: npm run lint
        pass_filenames: false
        files: '\.(ts|js|json|jsonc)$'
        language: system
      - id: worker-typecheck
        name: worker typecheck
        entry: npm run typecheck
        pass_filenames: false
        files: '\.(ts|jsonc?)$'
        language: system
