#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

docker-compose build
docker-compose push
ssh diraven@diraven.com 'cd /home/crabot/ && docker-compose pull'
ssh diraven@diraven.com 'cd /home/crabot/ && docker-compose run -T frontend ./manage.py migrate'
ssh diraven@diraven.com 'cd /home/crabot/ && docker-compose up -d --force-recreate'
