[tool.poetry]
name = "traveller"
version = "0.1.0"
description = ""
authors = ["DiRaven"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.3.1"
aiohttp = "^3.8.4"
beautifulsoup4 = "^4.12.2"
alembic = "^1.11.1"
sentry-sdk = "^1.28.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
pylint = "^2.17.4"
isort = "^5.12.0"
pre-commit = "^3.3.3"
bandit = "^1.7.5"
types-beautifulsoup4 = "^4.12.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "missing-class-docstring,missing-function-docstring,missing-module-docstring"
