#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

docker-compose run --rm app flake8 /app | sed -e "s|^/app|$(pwd)/bot|"
docker-compose run --rm app mypy /app | sed -e "s|^|$(pwd)/bot/|"
