#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
#set -o xtrace

# Runs checks and tests like CI pipeline does with few notable exceptions.
# Migrations-related tests that influence database state will not run by default.

die () {
    echo >&2 "$@"
    exit 1
}

[[ "$#" -eq 2 ]] || die "2 arguments required: 'test [bot|frontend]', $# provided"

docker-compose run $2 run-parts --exit-on-error continuous_integration/tests | sed -e "s|/app|$(pwd)/bot|"
