#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
set -o xtrace

python -m venv .tmpvenv
.tmpvenv/bin/pip install --no-cache-dir --requirement app/requirements.txt
.tmpvenv/bin/pip freeze > app/requirements.frozen.txt
rm -rf .tmpvenv
