# Generated by Django 2.0.6 on 2018-06-30 10:52

from django.db import migrations
from django.db.migrations import RunPython


def fnc(apps, schema_editor):
    Module = apps.get_model('mydiscord', 'Module')
    Module.objects.get_or_create(name='discord')
    Module.objects.get_or_create(name='base')


class Migration(migrations.Migration):
    dependencies = [
        ('mydiscord', '0002_alias'),
    ]

    operations = [
        RunPython(fnc, RunPython.noop)
    ]
