# Generated by Django 2.0.6 on 2018-07-01 13:40

from django.db import migrations
from django.db.migrations import RunPython


def fnc(apps, schema_editor):
    Module = apps.get_model('mydiscord', 'Module')
    m = Module.objects.get(name='base')
    m.name = 'mydiscord'
    m.save()


class Migration(migrations.Migration):
    dependencies = [
        ('mydiscord', '0008_auto_20180701_1331'),
    ]

    operations = [
        RunPython(fnc, RunPython.noop)
    ]
