# Generated by Django 2.1.4 on 2018-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0014_auto_20181027_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='discord_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
