# Generated by Django 2.2.1 on 2019-05-25 15:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theburningclaw', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together={('owner', 'kind')},
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('lootables', models.ManyToManyField(to='theburningclaw.ThingKind')),
            ],
        ),
        migrations.CreateModel(
            name='Lootable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('count_deviation', models.PositiveIntegerField()),
                ('thing_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theburningclaw.ThingKind')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theburningclaw.Venture')),
            ],
            options={
                'unique_together': {('venture', 'thing_kind')},
            },
        ),
    ]
