# Generated by Django 2.2.1 on 2019-05-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theburningclaw', '0002_auto_20190525_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venture',
            name='lootables',
        ),
    ]
