# Generated by Django 2.2.1 on 2019-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theburningclaw', '0003_remove_venture_lootables'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='lootables',
            field=models.ManyToManyField(through='theburningclaw.Lootable', to='theburningclaw.ThingKind'),
        ),
    ]
