"""empty message

Revision ID: 350a61cfbf1f
Revises:
Create Date: 2023-07-09 09:25:35.842200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "350a61cfbf1f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("log_channel_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("guild")
    # ### end Alembic commands ###
