"""empty message

Revision ID: e540035604ef
Revises: a5766648953a
Create Date: 2023-07-11 14:38:52.585476

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e540035604ef"
down_revision = "a5766648953a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guild", "log_channel_id", new_column_name="bans_sharing_channel_id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guild", "bans_sharing_channel_id", new_column_name="log_channel_id"
    )
    # ### end Alembic commands ###
