#!/usr/bin/env bash
NAME=${1%/}
USER="crabot"
HOST="diraven.com"

cd ${NAME} &&
go build &&
scp ${NAME} ${USER}@${HOST}:~/bin/${NAME}_new &&
ssh ${USER}@${HOST} supervisorctl stop crabot_${NAME}
ssh ${USER}@${HOST} rm /home/crabot/bin/${NAME} &&
ssh ${USER}@${HOST} mv /home/crabot/bin/${NAME}_new /home/crabot/bin/${NAME} &&
ssh ${USER}@${HOST} supervisorctl start crabot_${NAME} &&
rm ${NAME}

echo "DONE"