# Generated by Django 2.0.6 on 2018-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0006_auto_20180701_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='target',
            field=models.CharField(max_length=64),
        ),
    ]
