# Generated by Django 2.0.6 on 2018-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0007_auto_20180701_1328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('guild', 'source')},
        ),
    ]
