# Generated by Django 2.1.2 on 2018-10-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0009_auto_20180701_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='uid',
            new_name='discord_uid',
        ),
    ]
