# Generated by Django 2.1.2 on 2018-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0012_auto_20181027_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='trigger',
            field=models.CharField(default='.', max_length=1),
        ),
    ]
