# Generated by Django 2.1.2 on 2018-10-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0013_guild_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='discord_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
