# Generated by Django 2.1.4 on 2018-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0015_auto_20181204_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.TextField(),
        ),
    ]
