# Generated by Django 2.2 on 2019-04-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0016_auto_20181209_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='name',
        ),
    ]
