# Generated by Django 2.0.6 on 2018-06-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=16)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='mydiscord.Guild')),
            ],
        ),
    ]
