# Generated by Django 2.1.2 on 2018-10-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiscord', '0010_auto_20181027_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='discord_uid',
            new_name='discord_id',
        ),
    ]
