FROM python:3.7
WORKDIR /app

COPY docker-entrypoint /usr/bin/docker-entrypoint
ENTRYPOINT ["docker-entrypoint"]
CMD ["python", "main.py"]

RUN apt-get update && apt-get install wait-for-it man postgresql-client vim -y
COPY Pipfile.lock Pipfile /opt/
RUN pip install --upgrade pip pipenv && cd /opt/ && pipenv install --system --deploy --dev
