name: Continuous Integration
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Setup python dependencies
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.in-project true
          python -m poetry install

      - name: Run hooks
        run: python -m poetry run pre-commit run --all-files

      # - name: Build docker image
      #   run: |
      #     cp example.env .env
      #     docker-compose build
