// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CommandAlias string
	Guild        string
	GuildModules string
	Module       string
	Publicrole   string
}{
	CommandAlias: "command_alias",
	Guild:        "guild",
	GuildModules: "guild_modules",
	Module:       "module",
	Publicrole:   "publicrole",
}
