// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCommandAliases(t *testing.T) {
	t.Parallel()

	query := CommandAliases()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCommandAliasesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommandAliasesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CommandAliases().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommandAliasesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommandAliasSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommandAliasesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CommandAliasExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CommandAlias exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CommandAliasExists to return true, but got false.")
	}
}

func testCommandAliasesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	commandAliasFound, err := FindCommandAlias(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if commandAliasFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCommandAliasesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CommandAliases().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCommandAliasesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CommandAliases().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCommandAliasesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	commandAliasOne := &CommandAlias{}
	commandAliasTwo := &CommandAlias{}
	if err = randomize.Struct(seed, commandAliasOne, commandAliasDBTypes, false, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}
	if err = randomize.Struct(seed, commandAliasTwo, commandAliasDBTypes, false, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = commandAliasOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = commandAliasTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommandAliases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCommandAliasesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	commandAliasOne := &CommandAlias{}
	commandAliasTwo := &CommandAlias{}
	if err = randomize.Struct(seed, commandAliasOne, commandAliasDBTypes, false, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}
	if err = randomize.Struct(seed, commandAliasTwo, commandAliasDBTypes, false, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = commandAliasOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = commandAliasTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func commandAliasBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func commandAliasAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *CommandAlias) error {
	*o = CommandAlias{}
	return nil
}

func testCommandAliasesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &CommandAlias{}
	o := &CommandAlias{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, commandAliasDBTypes, false); err != nil {
		t.Errorf("Unable to randomize CommandAlias object: %s", err)
	}

	AddCommandAliasHook(boil.BeforeInsertHook, commandAliasBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	commandAliasBeforeInsertHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.AfterInsertHook, commandAliasAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	commandAliasAfterInsertHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.AfterSelectHook, commandAliasAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	commandAliasAfterSelectHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.BeforeUpdateHook, commandAliasBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	commandAliasBeforeUpdateHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.AfterUpdateHook, commandAliasAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	commandAliasAfterUpdateHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.BeforeDeleteHook, commandAliasBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	commandAliasBeforeDeleteHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.AfterDeleteHook, commandAliasAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	commandAliasAfterDeleteHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.BeforeUpsertHook, commandAliasBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	commandAliasBeforeUpsertHooks = []CommandAliasHook{}

	AddCommandAliasHook(boil.AfterUpsertHook, commandAliasAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	commandAliasAfterUpsertHooks = []CommandAliasHook{}
}

func testCommandAliasesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommandAliasesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(commandAliasColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommandAliasToOneGuildUsingGuild(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local CommandAlias
	var foreign Guild

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, commandAliasDBTypes, false, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, guildDBTypes, false, guildColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guild struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GuildID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Guild().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CommandAliasSlice{&local}
	if err = local.L.LoadGuild(ctx, tx, false, (*[]*CommandAlias)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Guild = nil
	if err = local.L.LoadGuild(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testCommandAliasToOneSetOpGuildUsingGuild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a CommandAlias
	var b, c Guild

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, commandAliasDBTypes, false, strmangle.SetComplement(commandAliasPrimaryKeyColumns, commandAliasColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, guildDBTypes, false, strmangle.SetComplement(guildPrimaryKeyColumns, guildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, guildDBTypes, false, strmangle.SetComplement(guildPrimaryKeyColumns, guildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Guild{&b, &c} {
		err = a.SetGuild(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Guild != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CommandAliases[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GuildID))
		reflect.Indirect(reflect.ValueOf(&a.GuildID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID, x.ID)
		}
	}
}

func testCommandAliasesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommandAliasesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommandAliasSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommandAliasesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommandAliases().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	commandAliasDBTypes = map[string]string{`GuildID`: `integer`, `ID`: `integer`, `Source`: `character varying`, `Target`: `character varying`}
	_                   = bytes.MinRead
)

func testCommandAliasesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(commandAliasPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(commandAliasColumns) == len(commandAliasPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCommandAliasesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(commandAliasColumns) == len(commandAliasPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommandAlias{}
	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, commandAliasDBTypes, true, commandAliasPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(commandAliasColumns, commandAliasPrimaryKeyColumns) {
		fields = commandAliasColumns
	} else {
		fields = strmangle.SetComplement(
			commandAliasColumns,
			commandAliasPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CommandAliasSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCommandAliasesUpsert(t *testing.T) {
	t.Parallel()

	if len(commandAliasColumns) == len(commandAliasPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CommandAlias{}
	if err = randomize.Struct(seed, &o, commandAliasDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommandAlias: %s", err)
	}

	count, err := CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, commandAliasDBTypes, false, commandAliasPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommandAlias struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommandAlias: %s", err)
	}

	count, err = CommandAliases().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
