// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPublicrolesPublicroles(t *testing.T) {
	t.Parallel()

	query := PublicrolesPublicroles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPublicrolesPublicrolesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesPublicrolesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PublicrolesPublicroles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesPublicrolesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PublicrolesPublicroleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesPublicrolesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PublicrolesPublicroleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PublicrolesPublicrole exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PublicrolesPublicroleExists to return true, but got false.")
	}
}

func testPublicrolesPublicrolesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	publicrolesPublicroleFound, err := FindPublicrolesPublicrole(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if publicrolesPublicroleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPublicrolesPublicrolesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PublicrolesPublicroles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPublicrolesPublicrolesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PublicrolesPublicroles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPublicrolesPublicrolesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	publicrolesPublicroleOne := &PublicrolesPublicrole{}
	publicrolesPublicroleTwo := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, publicrolesPublicroleOne, publicrolesPublicroleDBTypes, false, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}
	if err = randomize.Struct(seed, publicrolesPublicroleTwo, publicrolesPublicroleDBTypes, false, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = publicrolesPublicroleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = publicrolesPublicroleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PublicrolesPublicroles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPublicrolesPublicrolesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	publicrolesPublicroleOne := &PublicrolesPublicrole{}
	publicrolesPublicroleTwo := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, publicrolesPublicroleOne, publicrolesPublicroleDBTypes, false, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}
	if err = randomize.Struct(seed, publicrolesPublicroleTwo, publicrolesPublicroleDBTypes, false, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = publicrolesPublicroleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = publicrolesPublicroleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func publicrolesPublicroleBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func publicrolesPublicroleAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *PublicrolesPublicrole) error {
	*o = PublicrolesPublicrole{}
	return nil
}

func testPublicrolesPublicrolesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &PublicrolesPublicrole{}
	o := &PublicrolesPublicrole{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole object: %s", err)
	}

	AddPublicrolesPublicroleHook(boil.BeforeInsertHook, publicrolesPublicroleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleBeforeInsertHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.AfterInsertHook, publicrolesPublicroleAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleAfterInsertHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.AfterSelectHook, publicrolesPublicroleAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleAfterSelectHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.BeforeUpdateHook, publicrolesPublicroleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleBeforeUpdateHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.AfterUpdateHook, publicrolesPublicroleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleAfterUpdateHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.BeforeDeleteHook, publicrolesPublicroleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleBeforeDeleteHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.AfterDeleteHook, publicrolesPublicroleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleAfterDeleteHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.BeforeUpsertHook, publicrolesPublicroleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleBeforeUpsertHooks = []PublicrolesPublicroleHook{}

	AddPublicrolesPublicroleHook(boil.AfterUpsertHook, publicrolesPublicroleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	publicrolesPublicroleAfterUpsertHooks = []PublicrolesPublicroleHook{}
}

func testPublicrolesPublicrolesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPublicrolesPublicrolesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(publicrolesPublicroleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPublicrolesPublicroleToOneMydiscordGuildUsingGuild(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PublicrolesPublicrole
	var foreign MydiscordGuild

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, publicrolesPublicroleDBTypes, false, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, mydiscordGuildDBTypes, false, mydiscordGuildColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MydiscordGuild struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GuildID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Guild().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PublicrolesPublicroleSlice{&local}
	if err = local.L.LoadGuild(ctx, tx, false, (*[]*PublicrolesPublicrole)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Guild = nil
	if err = local.L.LoadGuild(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPublicrolesPublicroleToOneSetOpMydiscordGuildUsingGuild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PublicrolesPublicrole
	var b, c MydiscordGuild

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, publicrolesPublicroleDBTypes, false, strmangle.SetComplement(publicrolesPublicrolePrimaryKeyColumns, publicrolesPublicroleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, mydiscordGuildDBTypes, false, strmangle.SetComplement(mydiscordGuildPrimaryKeyColumns, mydiscordGuildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, mydiscordGuildDBTypes, false, strmangle.SetComplement(mydiscordGuildPrimaryKeyColumns, mydiscordGuildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*MydiscordGuild{&b, &c} {
		err = a.SetGuild(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Guild != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.GuildPublicrolesPublicroles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GuildID))
		reflect.Indirect(reflect.ValueOf(&a.GuildID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID, x.ID)
		}
	}
}

func testPublicrolesPublicrolesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPublicrolesPublicrolesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PublicrolesPublicroleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPublicrolesPublicrolesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PublicrolesPublicroles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	publicrolesPublicroleDBTypes = map[string]string{`DiscordID`: `text`, `GuildID`: `integer`, `ID`: `integer`}
	_                            = bytes.MinRead
)

func testPublicrolesPublicrolesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(publicrolesPublicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(publicrolesPublicroleColumns) == len(publicrolesPublicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPublicrolesPublicrolesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(publicrolesPublicroleColumns) == len(publicrolesPublicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PublicrolesPublicrole{}
	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, publicrolesPublicroleDBTypes, true, publicrolesPublicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(publicrolesPublicroleColumns, publicrolesPublicrolePrimaryKeyColumns) {
		fields = publicrolesPublicroleColumns
	} else {
		fields = strmangle.SetComplement(
			publicrolesPublicroleColumns,
			publicrolesPublicrolePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PublicrolesPublicroleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPublicrolesPublicrolesUpsert(t *testing.T) {
	t.Parallel()

	if len(publicrolesPublicroleColumns) == len(publicrolesPublicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PublicrolesPublicrole{}
	if err = randomize.Struct(seed, &o, publicrolesPublicroleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PublicrolesPublicrole: %s", err)
	}

	count, err := PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, publicrolesPublicroleDBTypes, false, publicrolesPublicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PublicrolesPublicrole struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PublicrolesPublicrole: %s", err)
	}

	count, err = PublicrolesPublicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
