// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPublicroles(t *testing.T) {
	t.Parallel()

	query := Publicroles()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPublicrolesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Publicroles().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PublicroleSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPublicrolesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PublicroleExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Publicrole exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PublicroleExists to return true, but got false.")
	}
}

func testPublicrolesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	publicroleFound, err := FindPublicrole(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if publicroleFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPublicrolesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Publicroles().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPublicrolesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Publicroles().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPublicrolesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	publicroleOne := &Publicrole{}
	publicroleTwo := &Publicrole{}
	if err = randomize.Struct(seed, publicroleOne, publicroleDBTypes, false, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}
	if err = randomize.Struct(seed, publicroleTwo, publicroleDBTypes, false, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = publicroleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = publicroleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Publicroles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPublicrolesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	publicroleOne := &Publicrole{}
	publicroleTwo := &Publicrole{}
	if err = randomize.Struct(seed, publicroleOne, publicroleDBTypes, false, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}
	if err = randomize.Struct(seed, publicroleTwo, publicroleDBTypes, false, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = publicroleOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = publicroleTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func publicroleBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func publicroleAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Publicrole) error {
	*o = Publicrole{}
	return nil
}

func testPublicrolesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Publicrole{}
	o := &Publicrole{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, publicroleDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Publicrole object: %s", err)
	}

	AddPublicroleHook(boil.BeforeInsertHook, publicroleBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	publicroleBeforeInsertHooks = []PublicroleHook{}

	AddPublicroleHook(boil.AfterInsertHook, publicroleAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	publicroleAfterInsertHooks = []PublicroleHook{}

	AddPublicroleHook(boil.AfterSelectHook, publicroleAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	publicroleAfterSelectHooks = []PublicroleHook{}

	AddPublicroleHook(boil.BeforeUpdateHook, publicroleBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	publicroleBeforeUpdateHooks = []PublicroleHook{}

	AddPublicroleHook(boil.AfterUpdateHook, publicroleAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	publicroleAfterUpdateHooks = []PublicroleHook{}

	AddPublicroleHook(boil.BeforeDeleteHook, publicroleBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	publicroleBeforeDeleteHooks = []PublicroleHook{}

	AddPublicroleHook(boil.AfterDeleteHook, publicroleAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	publicroleAfterDeleteHooks = []PublicroleHook{}

	AddPublicroleHook(boil.BeforeUpsertHook, publicroleBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	publicroleBeforeUpsertHooks = []PublicroleHook{}

	AddPublicroleHook(boil.AfterUpsertHook, publicroleAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	publicroleAfterUpsertHooks = []PublicroleHook{}
}

func testPublicrolesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPublicrolesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(publicroleColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPublicroleToOneGuildUsingGuild(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Publicrole
	var foreign Guild

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, publicroleDBTypes, false, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, guildDBTypes, false, guildColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guild struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.GuildID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Guild().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PublicroleSlice{&local}
	if err = local.L.LoadGuild(ctx, tx, false, (*[]*Publicrole)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Guild = nil
	if err = local.L.LoadGuild(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Guild == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPublicroleToOneSetOpGuildUsingGuild(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Publicrole
	var b, c Guild

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, publicroleDBTypes, false, strmangle.SetComplement(publicrolePrimaryKeyColumns, publicroleColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, guildDBTypes, false, strmangle.SetComplement(guildPrimaryKeyColumns, guildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, guildDBTypes, false, strmangle.SetComplement(guildPrimaryKeyColumns, guildColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Guild{&b, &c} {
		err = a.SetGuild(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Guild != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Publicroles[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.GuildID))
		reflect.Indirect(reflect.ValueOf(&a.GuildID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.GuildID != x.ID {
			t.Error("foreign key was wrong value", a.GuildID, x.ID)
		}
	}
}

func testPublicrolesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPublicrolesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PublicroleSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPublicrolesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Publicroles().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	publicroleDBTypes = map[string]string{`DiscordID`: `text`, `GuildID`: `integer`, `ID`: `integer`}
	_                 = bytes.MinRead
)

func testPublicrolesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(publicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(publicroleColumns) == len(publicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPublicrolesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(publicroleColumns) == len(publicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Publicrole{}
	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicroleColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, publicroleDBTypes, true, publicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(publicroleColumns, publicrolePrimaryKeyColumns) {
		fields = publicroleColumns
	} else {
		fields = strmangle.SetComplement(
			publicroleColumns,
			publicrolePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PublicroleSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPublicrolesUpsert(t *testing.T) {
	t.Parallel()

	if len(publicroleColumns) == len(publicrolePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Publicrole{}
	if err = randomize.Struct(seed, &o, publicroleDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Publicrole: %s", err)
	}

	count, err := Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, publicroleDBTypes, false, publicrolePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Publicrole struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Publicrole: %s", err)
	}

	count, err = Publicroles().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
